-- MySQL Script generated by MySQL Workbench
-- Tue Jul  5 03:21:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema exercises
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercises
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercises` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `exercises` ;

-- -----------------------------------------------------
-- Table `exercises`.`товар`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercises`.`товар` (
  `КодТовара` VARCHAR(20) NOT NULL,
  `Название` VARCHAR(50) NULL DEFAULT NULL,
  `КатегорияТовара` CHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`КодТовара`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `exercises`.`продажастрока`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercises`.`продажастрока` (
  `НомерДокумента` VARCHAR(20) NOT NULL,
  `КодТовара` VARCHAR(45) NOT NULL,
  `Кол-во` INT NULL DEFAULT NULL,
  `Цена` DECIMAL(18,2) NULL DEFAULT NULL,
  PRIMARY KEY (`НомерДокумента`, `КодТовара`),
  INDEX `id_idx` (`КодТовара` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`КодТовара`)
    REFERENCES `exercises`.`товар` (`КодТовара`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `exercises`.`продажазаголовок`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercises`.`продажазаголовок` (
  `НомерДокумента` VARCHAR(20) NOT NULL,
  `ДатаДокумента` DATETIME NULL DEFAULT NULL,
  `Клиент` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`НомерДокумента`, `Клиент`),
  CONSTRAINT `id`
    FOREIGN KEY (`НомерДокумента`)
    REFERENCES `exercises`.`продажастрока` (`НомерДокумента`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `exercises`.`клиент`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercises`.`клиент` (
  `КодКлиента` VARCHAR(20) NOT NULL,
  `Фамилия` VARCHAR(30) NULL DEFAULT NULL,
  `Имя` VARCHAR(30) NULL DEFAULT NULL,
  `Отчество` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`КодКлиента`),
  CONSTRAINT `id`
    FOREIGN KEY (`КодКлиента`)
    REFERENCES `exercises`.`продажазаголовок` (`Клиент`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
